# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.13

# Mod Properties
mod_version=2.3.2
maven_group=com.portablestorage
archives_base_name=portablestorage

# Dependencies
fabric_version=0.153.0+26.2
night_config_version=3.8.3
# https://modrinth.com/mod/yacl/versions
yacl_version=3.9.5+26.2-fabric
jpinyin_version=1.1.8
# https://modrinth.com/mod/jei/versions
jei_version=30.3.0.20
# https://modrinth.com/mod/modmenu/versions
modmenu_version=20.0.0-beta.4