# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.17.2
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=2.0.6
maven_group=com.portablestorage
archives_base_name=portablestorage

# Dependencies
fabric_version=0.92.6+1.20.1
cca_version=5.2.3
night_config_version=3.6.7
yacl_version=3.6.6+1.20.1-fabric
jpinyin_version=1.1.8
jei_version=15.20.0.129
emi_version=1.1.22+1.20.1
