[client]
# 是否偏移背包界面 (true: 上移并显示仓库, false: 保持原样)
offsetInventory = true

# 是否隐藏配方书按钮 (如果 offsetInventory 为 true，此项将被强制视为 true)
hideRecipeBook = true

[server]
# 是否启用 3x3 背包合成功能
enable3x3Crafting = true

# 是否在玩家死亡时禁用仓库 (true: 禁用, false: 保留)
dropStorageOnDeath = true

# 仓库储存最大种类数 (-1: 不限制)
maxStorageTypes = -1

# 仓库储存物品最大堆叠数 (-1: 不限制)
maxItemStackSize = -1

# 基础仓库储存最大种类数
baseMaxStorageTypes = 54

# 基础仓库储存物品最大堆叠数 (-1: 不限制)
baseMaxItemStackSize = -1
